const versiculos = [
    "Salmo 23:1 - El Señor es mi pastor, nada me faltará.",
    "Filipenses 4:13 - Todo lo puedo en Cristo que me fortalece.",
    "Juan 14:6 - Yo soy el camino, la verdad y la vida.",
    "Proverbios 3:5 - Confía en el Señor con todo tu corazón.",
    "Isaías 41:10 - No temas, porque yo estoy contigo.",
    "Mateo 5:9 - Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.",
    "Salmo 118:24 - Este es el día que hizo el Señor; regocijémonos y alegrémonos en él.",
    "Jeremías 29:11 - Porque yo sé los planes que tengo para ustedes, planes de bienestar y no de calamidad.",
    "Romanos 8:28 - Sabemos que Dios dispone todas las cosas para el bien de los que lo aman.",
    "Salmo 46:1 - Dios es nuestro refugio y fortaleza, nuestro pronto auxilio en las tribulaciones.",
    "1 Corintios 16:14 - Hagan todo con amor.",
    "Salmo 37:4 - Deléitate en el Señor, y él te concederá los deseos de tu corazón.",
    "Mateo 7:7 - Pidan, y se les dará; busquen, y hallarán; llamen, y se les abrirá.",
    "Isaías 40:31 - Pero los que esperan en el Señor renovarán sus fuerzas.",
    "Josué 1:9 - Sé fuerte y valiente. No temas ni te desanimes, porque el Señor tu Dios estará contigo dondequiera que vayas.",
    "Romanos 12:12 - Alégrense en la esperanza, muestren paciencia en el sufrimiento, perseveren en la oración.",
    "Salmo 121:1-2 - Levanto mis ojos a los montes; ¿de dónde vendrá mi ayuda? Mi ayuda viene del Señor, creador del cielo y de la tierra.",
    "Proverbios 16:3 - Pon en manos del Señor todas tus obras, y tus proyectos se cumplirán.",
    "Filipenses 4:6 - No se inquieten por nada; más bien, en toda ocasión, presenten sus peticiones a Dios en oración.",
    "Juan 16:33 - En el mundo tendrán aflicción; pero confíen, yo he vencido al mundo.",
    "2 Corintios 5:7 - Vivimos por fe, no por vista.",
    "Gálatas 6:9 - No nos cansemos de hacer el bien, porque a su debido tiempo cosecharemos si no desmayamos.",
    "1 Pedro 5:7 - Depositen en él toda ansiedad, porque él cuida de ustedes.",
    "Salmo 91:1 - El que habita al abrigo del Altísimo se acoge a la sombra del Todopoderoso.",
    "Mateo 28:20 - Yo estaré con ustedes todos los días, hasta el fin del mundo.",
    "Juan 8:12 - Yo soy la luz del mundo; el que me sigue no andará en tinieblas."
  "Isaías 26:3 - Al de carácter firme lo guardarás en perfecta paz, porque en ti confía.",
    "Salmo 34:8 - Gusten y vean que el Señor es bueno; dichoso el que en él se refugia.",
    "Hebreos 11:1 - La fe es la certeza de lo que se espera, la convicción de lo que no se ve.",
    "Salmo 55:22 - Encomienda al Señor tus afanes, y él te sostendrá.",
    "Mateo 11:28 - Vengan a mí todos ustedes que están cansados y agobiados, y yo les daré descanso.",
    "Efesios 6:11 - Vístanse de toda la armadura de Dios para que puedan hacer frente a las artimañas del diablo.",
    "1 Juan 4:19 - Nosotros amamos porque él nos amó primero.",
    "Romanos 15:13 - Que el Dios de la esperanza los llene de todo gozo y paz a ustedes que creen en él.",
    "Proverbios 18:10 - Torre fuerte es el nombre del Señor; a ella corre el justo y se pone a salvo.",
    "Isaías 43:2 - Cuando cruces las aguas, yo estaré contigo; cuando cruces los ríos, no te cubrirán sus aguas.",
    "2 Timoteo 1:7 - Porque Dios no nos ha dado un espíritu de cobardía, sino de poder, de amor y de dominio propio.",
    "Salmo 30:5 - Por la noche durará el lloro, y a la mañana vendrá la alegría.",
    "1 Tesalonicenses 5:16-18 - Estén siempre alegres, oren sin cesar, den gracias en toda situación.",
    "Lamentaciones 3:22-23 - Grande es su fidelidad; sus misericordias son nuevas cada mañana.",
    "Éxodo 14:14 - El Señor peleará por ustedes; ustedes quédense quietos.",
    "Sofonías 3:17 - El Señor tu Dios está en medio de ti como guerrero que salva; se gozará por ti con alegría.",
    "Salmo 37:5 - Encomienda al Señor tu camino; confía en él, y él actuará.",
    "Proverbios 4:23 - Sobre toda cosa guardada, guarda tu corazón, porque de él mana la vida.",
    "Isaías 40:29 - Él da esfuerzo al cansado y multiplica las fuerzas al que no tiene ninguna.",
    "Hebreos 13:8 - Jesucristo es el mismo ayer, hoy y por los siglos."
];

const randomIndex = Math.floor(Math.random() * versiculos.length);
document.getElementById('versiculoTexto').textContent = versiculos[randomIndex];
